{{- if and (ne .Values.global.registry_location "on-cluster") (ne .Values.global.registry_location "off-cluster") }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drycc-registry-token-refresher
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-registry-token-refresher
  template:
    metadata:
      labels:
        app: drycc-registry-token-refresher
    spec:
      containers:
        - name: drycc-registry-token-refresher
          image: {{.Values.docker_registry}}{{.Values.org}}/registry-token-refresher:{{.Values.docker_tag}}
          imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          env:
            - name: "DRYCC_REGISTRY_LOCATION"
              value: "{{ .Values.global.registry_location }}"
            - name: "DRYCC_REGISTRY_SECRET_PREFIX"
              value: "{{ .Values.global.secret_prefix }}"
            - name: DRYCC_NAMESPACE_REFRESH_TIME
              value: "5"
            - name: "DRYCC_TOKEN_REFRESH_TIME"
              value: "{{ .Values.token_refresh_time }}"
          volumeMounts:
            - name: registry-secret
              mountPath: /var/run/secrets/drycc/objectstore/creds
              readOnly: true
      volumes:
        - name: registry-secret
          secret:
            secretName: registry-secret
{{- end }}
